### ISSUE TITLE
tone(pin, freq, duration)

### ISSUE THREAD

**Issue by microwattbott** [adafruit/Adafruit_CircuitPython_SimpleIO#19]
While testing an early beta version of  piezo_music.py,  
I struggled to understand that freq had to be an integer.  
The program's float value is not going to make the tone() function work.  
@tannewt  suggested that we try to "fix tone to either handle it or produce a friendly error message."

RE:   \Metro Experimenter Guide\METROX-Examples-and-Project-Sketches-master\circuitpython\CIRC06\piezo_music.py

**Comment by brentru** [comment]
Thanks for the feedback! I'm going to wire up the circuit for piezo_music.py and fix it per @tannewt's suggestions (thx for including those btw!)

**Comment by brentru** [comment]
Tone function has been changed, and piezo_music.py in the MetroX circuit examples has been updated.
