### ISSUE TITLE
map_range not allowing output range reversal

### ISSUE THREAD

**Issue by CedarGroveStudios** [adafruit/Adafruit_CircuitPython_SimpleIO#21]
After testing, I noticed that the simpleio.map_range function doesn't allow the upper boundary of the output range to be smaller than the lower boundary. The Arduino map() function allows it so that you can reverse the output range. Here's the original simpleio.map_range code:  

def map_range(x, in_min, in_max, out_min, out_max):
    return max(min((x-in_min) * (out_max - out_min) / (in_max-in_min) + out_min, out_max), out_min)

and the fix I used for my project: 

def map_range(x, in_min, in_max, out_min, out_max):
    if out_min <= out_max:
        return max(min((x-in_min) * (out_max - out_min) / (in_max-in_min) + out_min, out_max), out_min)
    else:
        return min(max((x-in_min) * (out_max - out_min) / (in_max-in_min) + out_min, out_max), out_min)

Also, the annotation should list that the map_range function is equivalent to the combination of the Arduino map() and constrain() functions since it limits the returned value to the specified output range. Not knowing that could create rare issues when using map_range to convert Arduino sketches to CircuitPython.

**Comment by tannewt** [comment]
Done in #22
