### ISSUE TITLE
Simpleio inconsistent behavior between CP releases

### ISSUE THREAD

**Issue by hukuzatuna** [adafruit/Adafruit_CircuitPython_SimpleIO#29]
In testing the PWM section of the CircuitPython guide, I got different results than Kattni. On investigation, I discovered simpleio appears to be broken under CircuitPython 3.0 Alpha 2 where the same code and hardware work as expected under 2.2.4. 

The tutorial I was checking is [https://learn.adafruit.com/circuitpython-essentials/circuitpython-pwm?preview_token=hBVvTKWl_ifgsJckceOXFg](https://learn.adafruit.com/circuitpython-essentials/circuitpython-pwm?preview_token=hBVvTKWl_ifgsJckceOXFg)

Here is the spreadsheet with my results and findings: 
[pwm_testing.xlsx](https://github.com/adafruit/Adafruit_CircuitPython_SimpleIO/files/1800030/pwm_testing.xlsx)

Sometimes the piezo will beep intermittently, and sometimes the test will not work at all (under 3.0) when the test behaved as expected under 2.2.24.

**Comment by tannewt** [comment]
I've confirmed this on the Metro M0 Express. It works fine if I print a value but without it, it doesn't. Weird!

**Comment by tannewt** [comment]
The Metro M4 Express fails on A0 because there are no timers for it. On A2 the only timer channel is 0 which is used internally to adjust the frequency. Sorry!

Fix incoming for the M0.
