### ISSUE TITLE
Remove Servo

### ISSUE THREAD

**Issue by tannewt** [adafruit/Adafruit_CircuitPython_SimpleIO#33]
[adafruit_motor.servo](https://github.com/adafruit/Adafruit_CircuitPython_Motor/blob/master/adafruit_motor/servo.py) is better because it also supports continuous Servos.

Guides will also need to be updated.

**Comment by brentru** [comment]
Guides which reference simpleio servo:

- [x]  https://learn.adafruit.com/circuitpython-essentials/circuitpython-servo
- [x]  https://learn.adafruit.com/combo-dial-safe-with-circuit-playground-express?view=all#code-with-circuitpython

**Comment by sommersoft** [comment]
This looks to be fixed by #34. Reopen if I'm mistaken...

**Comment by sommersoft** [comment]
On Discord, user Faeylayn, reported that the [CPX Perk Up Ears](https://learn.adafruit.com/perk-up-ears/code) guide still references `simpleio.servo`. That guide needs to be updated.

tagging for attention: @dastels

**Comment by dastels** [comment]
I'm on it.

**Comment by dastels** [comment]
PR submitted

**Comment by dhalbert** [comment]
[ ] Another guide that uses `simpleio.Servo`: https://learn.adafruit.com/trinket-gemma-servo-control/circuitpython-code
Author is @mikeysklar

Noted by forum user here: https://forums.adafruit.com/viewtopic.php?f=60&t=142377

**Comment by mikeysklar** [comment]
I'll go ahead and update this guide to use adafruit_motor.servo in place of simpleio.Servo.

**Comment by mikeysklar** [comment]
PR submitted and approved for Trinket Gemma Servo Control. The guide has been updated to use adafruit_motor.servo and an update was posted in the forum.

**Comment by kattni** [comment]
Looks like this was taken care of. We can reopen it if we run into more instances needing an update.
