### ISSUE TITLE
tone() will not work on nrf52840

### ISSUE THREAD

**Issue by Tasm-Devil** [adafruit/Adafruit_CircuitPython_SimpleIO#38]
Hi,

i get a **NameError** when calling `tone()` a second time. 
Line 63 `square_wave_sample = audioio.RawSample(square_wave)` uses a module that is probably not imported on some boards (e.g. nrf52840 Express).

Line 63 should never been executed but it will because a **ValueError** is thrown in Line 53 when calling `tone()` and creating the `PWMOut`-Object a second time.

Thats strange because you would assume, using the with-statement will deinitialize the used Pin. I assume, the deinit is faulty.

Anyone an idea, where to fix this.

**Comment by kattni** [comment]
I'm not sure what the problem was at the time that this issue was created. CircuitPython has had updates since that time that are now the reason why the nRF52840 doesn't work with `simpleio.tone()`. Closing in favor of #45.
