### ISSUE TITLE
maybe pulseout/pulsein?

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_SimpleIO#5]
precision pulses!

**Comment by tannewt** [comment]
Whats an example for this? Is it different from PWM?

**Comment by ladyada** [comment]
pulse in is good if you want to measure a sensor with couple millisec pulse input - some inexpensive sonar sensors do this. having precision pulse output can be useful for some cases that i cant think of but i can imagine wanting to generate a one-time pulse could be handy for scientific projects?

**Comment by ladyada** [comment]
we did this!
