### ISSUE TITLE
Provide map_range() in a new library

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_SimpleIO#57]
The most common reason to use this library is just for `map_range()`. We can consider creating a new `MapRange` library just for that purpose. It will be very small. Perhaps there are a few other similar utility functions we could put in as well.

**Comment by jedgarpark** [comment]
I dig it, that's definitely the main reason I import simpleio.

**Comment by dhalbert** [comment]
Fixed by adding new library https://github.com/adafruit/Adafruit_CircuitPython_SimpleMath.
