### ISSUE TITLE
Any considerations to expanding the functionality of SimpleIO?

### ISSUE THREAD

**Issue by gus7av** [adafruit/Adafruit_CircuitPython_SimpleIO#65]
Hello!

I think it would be nice to have more IO types and other basic functionality. 
I've made a try myself here: https://github.com/gus7av/circuitpython_essentials/blob/main/README.md.
I think it could be easier to recommend circuitpython to beginners, if there was an official helper library that could reduce the amount of code you need to remember in order to set up the basic IO-types. The helper library for the circuitpython express platform has been a really nice entry point for me. I'm thinking about something similar, but universal to all boards.  

Gustav

**Comment by tannewt** [comment]
I don't think we'd want to expand this library. I'm happy with our native APIs for the basics as described in https://learn.adafruit.com/circuitpython-essentials/ .

You are welcome to add your library to the community bundle: https://github.com/adafruit/CircuitPython_Community_Bundle

I strongly recommend against the style you have now using `lower_case` for class names when `CamelCase` is standard for Python. https://www.python.org/dev/peps/pep-0008/#class-names It's important to teach consistently from the start.
